# Generated by Django 3.1.5 on 2021-02-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210211_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.CharField(default='empty', max_length=64),
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(default='empty', max_length=64),
        ),
        migrations.AddField(
            model_name='listing',
            name='imgURL',
            field=models.URLField(default='www.google.ru'),
        ),
        migrations.AddField(
            model_name='listing',
            name='starting_bid',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(default='empty', max_length=64),
        ),
    ]
