# Generated by Django 3.1.5 on 2021-02-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210211_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='imgURL',
            field=models.URLField(default='https://harrypotter.fandom.com/wiki/Broomstick?file=Hpnbbrbkmk-w370.jpg'),
        ),
    ]
