# Generated by Django 3.1.5 on 2021-04-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210211_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='starting_bid',
            new_name='bid',
        ),
    ]
