# Generated by Django 3.1.5 on 2021-04-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210420_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='testfield',
            field=models.CharField(default='empty', max_length=64),
        ),
    ]
