# Generated by Django 3.1.5 on 2021-04-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_watchlist_testfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='testfield',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='title',
            field=models.CharField(default='empty', max_length=64),
        ),
    ]
