# Generated by Django 3.1.5 on 2021-04-26 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210426_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='last_bidder',
        ),
    ]
