# Generated by Django 3.1.5 on 2021-04-26 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_listing_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='status',
        ),
    ]
